name: 'Resource Packager'
description: 'Generate .zip files (and sha1 hashes) from files for Minecraft Server Resource Packs.'
author: 'Soumeh'
inputs:
  filename:
    description: 'The name of the built pack'
  items:
    description: 'The folders / files to be built into the pack'
  optimize-jsons:
    description: "Whether or not to optimize any .json (and .mcmeta json) files to lower their size."
    default: 'true'
  gen-sha1:
    description: 'Whether or not to generate a Sha1 hash of the built pack'
    default: 'false'
    required: false
  output-folder:
    description: 'The directory to output files in'
    default: 'build'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "folder-plus"