name: 'build-resource-pack'
description: 'Generate .zip files from folders (and also Sha1 hashes) for Minecraft server resource packs'
author: 'Soumeh'
inputs:
  filename:
    description: 'The name of the built pack'
  items:
    description: 'The folders / files to be built into the pack'
  gen-sha1:
    description: 'Whether or not to generate a Sha1 hash of the built pack'
    default: 'false'
    required: false
  output-folder:
    description: 'The directory to output files in'
    default: 'build'
    required: false

runs:
  using: "docker"
  image: "Dockerfile"