name: 'Resource Packager'
description: 'Generate .zip files (and sha1 hashes) from files for Minecraft Server Resource Packs.'
author: 'Sorrowfall'
inputs:
  parts:
    description: 'A list of directories to make the Resource Pack out of.'
    required: true
  name:
    description: 'What to name the created Resource Pack.'
    default: 'pack'
    required: false
  output_directory:
    description: 'What directory to make the Resource Pack in.'
    default: 'build'
    required: false
  optimize_jsons:
    description: "Whether or not to optimize JSON files."
    default: 'true'
    required: false
branding:
  icon: "folder-plus"
runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/resource-packager -p ${{ inputs.items }} -n ${{ inputs.name }} -d ${{ inputs.output_directory }} -o ${{ inputs.optimize_jsons }}
      shell: bash