name: 'Resource Packager'
description: 'Generate .zip files (and sha1 hashes) from files for Minecraft Server Resource Packs.'
author: 'Sorrowfall'
inputs:
  parts:
    description: 'A list of directories to make the Resource Pack out of.'
    required: true
  name:
    description: 'What to name the created Resource Pack.'
    default: 'pack'
    required: false
  output-directory:
    description: 'What directory to make the Resource Pack in.'
    default: 'build'
    required: false
  optimize-jsons:
    description: "Whether or not to optimize JSON files."
    default: 'true'
    required: false
outputs:
  parts:
    description: 'The SHA-1 hash of the Resource Pack.'
    value: ${{ steps.resource-packager.outputs.hash }}
branding:
  icon: "folder-plus"
  color: "red"
runs:
  using: "composite"
  steps:
    - id: resource-packager
      run: echo $(python ${{ github.action_path }}/resource-packager -g -n ${{ inputs.name }} -d ${{ inputs.output-directory }} -o ${{ inputs.optimize-jsons }} -p ${{ inputs.items }})
      shell: bash
